services:
  app:
    build: .
    container_name: nuke
    ports:
      - '${APP_PORT}:80'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./:/var/www/html
    environment:
      - OPCACHE_VALIDATE_TIMESTAMPS=1

  db:
    image: postgres:16
    container_name: nuke_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Укажи свой пароль
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      retries: 5
      start_period: 5s

  redis:
    image: redis:latest
    container_name: nuke_redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
